# File Tree: AI

**Generated:** 3/16/2026, 10:15:37 AM
**Root Path:** `c:\Users\nsere\Desktop\vsc files\AI`

```
├── 📁 templete
│   ├── 📁 static
│   │   └── 🎨 style.css
│   └── 🌐 index.html
├── 🖼️ API PIC.png
├── 🐍 app.py
├── 📄 chat_memory.db
├── 🐍 database.py
├── 📝 readMe.md
└── 📄 requirement.txt
```

---
*Generated by FileTree Pro Extension*